### PR TITLE
Update to LibreNMS 23.11.0

### PR DESCRIPTION
**Pull request by rybnico**
Update LibreNMS to Version 23.10.0, released 2023-10-26

### CODE REVIEW

**Comment by rybnico** [comment]
@crazy-max Any chance of this being merged soon? LibreNMS 23.10.0 was released > 2 weeks ago. Would be great to keep up with upstream. Thanks anyway :)

**Comment by rybnico** [comment]
> I suggest upgrading to 23.11.0 instead. 23.11.0 is mostly a bugfix release.

But 23.11.0 has not been released yet... and 23.10.0 contains some security fixes.

**Comment by murrant** [comment]
23.11.0 is released.

**Comment by rybnico** [comment]
I updated this PR for 23.11.0

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
