### PR TITLE
Fix issue with alerts not functioning correctly.

### PR DESCRIPTION
**Pull request by Aterfax**
This should address the issues mentioned in https://github.com/librenms/docker/issues/297

Does not look like I can link the PR to the issue to close it however.

### CODE REVIEW

**Review by crazy-max — APPROVED** [review]

**Comment by murrant** [comment]
Hmm, I wonder why that would be.  Upstream it already should default to tcp. https://github.com/librenms/librenms/blob/master/config/database.php#L213

**Comment by Aterfax** [comment]
Yes, it is a bit odd as I read that in the docs for it too, At least for now setting it manually populates this correctly so we don''t have the error but I am not sure if this needs to be upstreamed to LibreNMS in general or predis as some kind of bug.

**Comment by murrant** [comment]
@Aterfax what do you have set for `REDIS_HOST`?  when I just run `docker compose up -d` in the examples/compose from here, it doesn't have an issue.

**Comment by Aterfax** [comment]
How odd, as it stands I have:

```bash
MEMORY_LIMIT=256M
MAX_INPUT_VARS=1000
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

CACHE_DRIVER=redis
SESSION_DRIVER=redis
REDIS_HOST=redis
REDIS_SCHEME=tcp

LIBRENMS_SNMP_COMMUNITY=REDACTED

LIBRENMS_WEATHERMAP=false
LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
```

Which would have been prior to my edit / fix:

```bash
MEMORY_LIMIT=256M
MAX_INPUT_VARS=1000
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

CACHE_DRIVER=redis
SESSION_DRIVER=redis
REDIS_HOST=redis

LIBRENMS_SNMP_COMMUNITY=REDACTED

LIBRENMS_WEATHERMAP=false
LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
```

The majority of any edits I have made are swapping the docker volumes for volume bind mounts to the host but I can't see how that could cause this?

**Review by crazy-max — APPROVED** [review]
@murrant I wonder if this is not linked to the new way YAML config is applied in https://github.com/librenms/docker/pull/225? Maybe the database was already populated with an empty `REDIS_SCHEME` so that's maybe why it works with a fresh db?

Anyway I think it's fine to have this in our examples. I will open another PR to set it if not specified just in case.

**Comment by crazy-max** [comment]
@murrant Oh I think I found why, we are setting an empty var if not defined: https://github.com/librenms/docker/blob/3c84a0a6b505e155165ddbb698c1f0c025559c02/rootfs/etc/cont-init.d/05-svc-dispatcher.sh#L101

I guess librenms checks just the env var existence but not its value and therefore applies an empty val in our case and does not use the default value.

**Pull request merged**
