### PR TITLE
Bump libreNMS to 24.8.1

### PR DESCRIPTION
**Pull request by mib1185**
release: https://github.com/librenms/librenms/releases/tag/24.8.0

not sure, if we should first bump to 24.7.0, so that all releases are available via docker?

### CODE REVIEW

**Comment by mib1185** [comment]
build issue seems to be fixed with https://github.com/librenms/librenms/pull/16303 - need to wait for bugfix release, than bump here

**Comment by murrant** [comment]
I plan to release a 24.8.1 release including that and an alerting bugfix.

**Comment by murrant** [comment]
24.8.1 is tagged now.

**Comment by mib1185** [comment]
Thanks @murrant for taking care about this 👍

**Review by crazy-max — APPROVED** [review]
LGTM

**Pull request merged**
