### PR TITLE
 LibreNMS 21.12.1

### PR DESCRIPTION
**Pull request by hjcday**
LibreNMS 21.12.0

### CODE REVIEW

**Review by crazy-max — CHANGES_REQUESTED** [review]
Remove changes from Changelog and squash commits thx.

**Comment by hjcday** [comment]
> Remove changes from Changelog and squash commits thx.

Should be right now

**Comment by Laplacence** [comment]
21.12.1 released so we need to upgrade it?

**Comment by crazy-max** [comment]
Looks like CI fails: https://github.com/librenms/docker/runs/4713256266?check_suite_focus=true#step:7:2860

**Comment by crazy-max** [comment]
@hjcday Can you rebase and squash please? Should be ok now.

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
