### PR TITLE
Dispatcher service sidecar

### PR DESCRIPTION
**Pull request by RyanMorash**
I tried taking a stab at building out a sidecar for my request in #67. I built the image on Docker Hub with these changes and am running it on the new system I am building without issues so far. The image is available at https://hub.docker.com/layers/ryanmorash/librenms-docker/DispatcherService/images/sha256-e04cd778c7d0646b66caa39eb26021c2da83eb8523347f76ef2d4baf1d8e0c74

### CODE REVIEW

**Comment by murrant** [comment]
I'm curious if this doesn't warrant a different layout.

The dispatcher in the main "librenms" container without any poller workers and a separate poller node container to do the work.  Not that familiar with docker so I could be making some wrong assumptions.

It would make sense not to have a cron option if the dispatcher service is working.

**Comment by RyanMorash** [comment]
I was simply copying the existing cron sidecar methodology for simplicity, but that definitely sounds like the better way of doing it. I’m not super familiar with docker myself, much less of any intricacies of this particular container so I think @crazy-max would need to chime in.

**Comment by crazy-max** [comment]
@murrant @RyanMorash Yes, I think there are other things to consider. In this image we use the `poller-wrapper.py`. Is it the same thing as `poller-service.py`?

**Comment by crazy-max** [comment]
@RyanMorash I have created a [dispatcher-service](https://github.com/librenms/docker/tree/dispatcher-service) branch with an implementation of the Dispatcher Service. Doc and examples have also been updated. Let's discussed this on #70

**Pull request closed without merging**
