### PR TITLE
bump librenms to 23.7.0

### PR DESCRIPTION
**Pull request by ryanmerolle**

### CODE REVIEW

**Review by crazy-max — CHANGES_REQUESTED** [review]
Please remove changes in the CHANGELOG, there are done right before the release and might not match the expected date.

**Comment by ryanmerolle** [comment]
not sure why the build fails but the test passes (which includes a build)

**Comment by crazy-max** [comment]
Seems to fail against `arm/v6` arch: https://github.com/librenms/docker/actions/runs/5357193145/jobs/9718195316?pr=359#step:7:5799

```
313.4 73 packages you are using are looking for funding.
313.4 Use the `composer fund` command to find out more!
325.0 > LibreNMS\ComposerHelper::postInstall
330.4 > Illuminate\Foundation\ComposerScripts::postInstall
330.4 > @php artisan vue-i18n:generate --multi-locales --format=umd
337.1 > @php artisan view:cache
342.9 Script @php artisan view:cache handling the post-install-cmd event returned with error code 135
```

**Comment by Laplacence** [comment]
Can this still be merged?

**Comment by Laplacence** [comment]
23.8.1 released

**Pull request closed without merging**
