### PR TITLE
Alpine Linux 3.19

### PR DESCRIPTION
**Pull request by crazy-max**

### CODE REVIEW

**Comment by crazy-max** [comment]
@murrant Looks like there is an issue with artisan since Alpine 3.18: https://github.com/librenms/docker/actions/runs/5627501785/job/15250103444?pr=361#step:5:957

```
 28.92 Generating optimized autoload files
32.09 > Illuminate\Foundation\ComposerScripts::postAutoloadDump
32.11 > @php artisan package:discover --ansi
32.48 
32.48 In Process.php line 434:
32.49                                                    
32.49   The process has been signaled with signal "11".  
32.49                                                    
32.49 
32.70 Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

I can't repro with another project using artisan after updating to Alpine 3.18: https://github.com/anonaddy/docker/actions/runs/5627716586/job/15250678966?pr=215#step:5:933 (https://github.com/anonaddy/docker/pull/215)

**Comment by murrant** [comment]
It looks like that is Laravel code and all it does is delete these three files:
bootstrap/cache/config.php
bootstrap/cache/services.php
bootstrap/cache/packages.php

They are prefixed with @, so I wonder if our error handler is not allowing them to be ignored.

**Comment by crazy-max** [comment]
> It looks like that is Laravel code and all it does is delete these three files: bootstrap/cache/config.php bootstrap/cache/services.php bootstrap/cache/packages.php
> 
> They are prefixed with @, so I wonder if our error handler is not allowing them to be ignored.

@murrant Still the same error after rebase with 23.11.0: https://github.com/librenms/docker/actions/runs/6990842153/job/19020755232?pr=361#step:7:2879

```
38.02 Generating optimized autoload files
42.95 > Illuminate\Foundation\ComposerScripts::postAutoloadDump
42.98 > @php artisan package:discover --ansi
43.53 
43.54 In Process.php line 436:
43.54                                                    
43.54   The process has been signaled with signal "11".  
43.54                                                    
43.54 
43.85 Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

I also tried by disabling composer autoloader with `--no-autoloader` but now get:

```
...
#16 30.21   - Installing symfony/yaml (v6.3.0): Extracting archive
#16 30.21   - Installing tecnickcom/tcpdf (6.6.2): Extracting archive
#16 30.21   - Installing tightenco/ziggy (v1.6.0): Extracting archive
#16 32.06 Package influxdb/influxdb-php is abandoned, you should avoid using it. No replacement was suggested.
#16 32.06 122 packages you are using are looking for funding.
#16 32.06 Use the `composer fund` command to find out more!
#16 32.50 > LibreNMS\ComposerHelper::postInstall
#16 32.50 
#16 32.50 In EnvHelper.php line 118:
#16 32.50
#16 32.50   [Error]
#16 32.50   Call to undefined function LibreNMS\Util\base_path()
#16 32.50
#16 32.50
#16 32.50 Exception trace:
#16 32.50   at /opt/librenms/LibreNMS/Util/EnvHelper.php:118
#16 32.50  LibreNMS\Util\EnvHelper::init() at /opt/librenms/LibreNMS/ComposerHelper.php:138
#16 32.50  LibreNMS\ComposerHelper::populateEnv() at /opt/librenms/LibreNMS/ComposerHelper.php:49
#16 32.50  LibreNMS\ComposerHelper::postInstall() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:450
#16 32.50  Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:257
#16 32.50  Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:129
#16 32.50  Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/bin/composer/src/Composer/Installer.php:394
#16 32.50  Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/InstallCommand.php:147
#16 32.50  Composer\Command\InstallCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:298
#16 32.50  Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:1040
#16 32.50  Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:301
#16 32.50  Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:382
#16 32.50  Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:171
#16 32.50  Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:145
#16 32.50  Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:93
#16 32.50  require() at /usr/bin/composer:29
```

**Comment by crazy-max** [comment]
@murrant Ok looks good with Alpine 3.19 :tada:

**Pull request merged**
