### PR TITLE
Bump to 24.9.1

### PR DESCRIPTION
**Pull request by santiag0z**

### CODE REVIEW

**Comment by murrant** [comment]
PHP will also need to be updated.

**Comment by jacobw** [comment]
Dockerfile already uses php82. Release notes say bump minimum to php to 8.2 so does php need to be updated @murrant ?

**Comment by crazy-max** [comment]
> PHP will also need to be updated.

Done in #459

@jacobw Can you rebase please?

**Review by crazy-max — CHANGES_REQUESTED** [review]
Can you rebase please since #459 has been merged?

**Pull request closed without merging**
